version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 238101178196.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=public.ecr.aws/i1i8s0z9/indeed-scraper
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating ECS service..."
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
      - echo "End of script"

artifacts:
  files:
    - '**/*'
  name: artifacts
